
trigger:
- master

#pool: 'Win8.1'
pool: 'Win2016'
#pool: 'Default'
#pool: 'AzureVms'

steps:

- task: ExecMicroFocusTestsDemo8@0
  inputs:
    SourcePath: 'C:\Scenarios-Multiple2\Scenarios-Single\Scenarios-Single\Scenarios-Single\Scenarios-Single'
    ResultsDirectory: 'C:\LRLRLR'
    ControllerPollingInterval: '50'
    ScenarioExecutionTimeout: '12'
    TreatFailuresAsErrors: false
    TaskTimeout: '1500'
    PublishScenarioResults: false
    PublishArtifactsManually: true
    BuildArtifactsDirectory: C:\PersonalArtifacts
    PublishTestReportsManually: true
    BuildTestReportsDirectory: C:\TestResults

# # The scenario will be stopped after the specified timeout
# - task: ExecMicroFocusTestsDemo8@0
#   inputs:
#     SourcePath: 'C:\Scenarios-Multiple\10UsersPassedScenario.lrs'
#     ScenarioExecutionTimeout: '1'
#   condition: always()


# #The task should fail because of the total timeout
# - task: ExecMicroFocusTestsDemo8@0
#   inputs:
#     SourcePath: 'C:\Scenarios-Multiple'
#     ScenarioExecutionTimeout: '1'
#     TaskTimeout: '10'
#   condition: always()
